import { createSafeDomainCode } from "../common/safe-domain-code.js";
import { createStringUnionValue } from "../common/string-union-value.js";
import {
  domainAggregateTypes,
  domainEventNames,
  type DomainAggregateType,
  type DomainEventName,
} from "./domain-event.js";

export const eventContractVersions = ["v1"] as const;

export type EventContractVersion = (typeof eventContractVersions)[number];

export const eventDataClassifications = ["public", "internal", "confidential"] as const;

export type EventDataClassification = (typeof eventDataClassifications)[number];

export const approvedIntegrationEventNames = [
  "instance.created.v1",
  "instance.connected.v1",
  "instance.disconnected.v1",
  "instance.logged_out.v1",
  "session.activated.v1",
  "session.expired.v1",
  "session.revoked.v1",
  "message.received.v1",
  "message.accepted.v1",
  "message.dispatched.v1",
  "message.delivered.v1",
  "message.read.v1",
  "message.failed.v1",
  "media.processed.v1",
  "media.failed.v1",
  "webhook.delivery.succeeded.v1",
  "webhook.delivery.failed.v1",
  "webhook.delivery.dead_lettered.v1",
  "guardrail.blocked.v1",
  "guardrail.throttled.v1",
  "health.degraded.v1",
  "health.recovered.v1",
] as const;

export type IntegrationEventName = (typeof approvedIntegrationEventNames)[number];

export type DomainEventContract = Readonly<{
  eventName: DomainEventName;
  signalName: string;
  version: EventContractVersion;
  aggregateType: DomainAggregateType;
  dataClassification: EventDataClassification;
  requiredData: readonly string[];
  optionalData: readonly string[];
  orderingRequirement: string;
  idempotencyRequirement: string;
  integrationEventName?: IntegrationEventName;
}>;

export type DomainEventContractInput = Readonly<{
  eventName: string;
  signalName: string;
  version: string;
  aggregateType: string;
  dataClassification: string;
  requiredData: readonly string[];
  optionalData?: readonly string[];
  orderingRequirement: string;
  idempotencyRequirement: string;
  integrationEventName?: string;
}>;

const integrationEventByDomainEvent: Partial<Record<DomainEventName, IntegrationEventName>> = {
  InstanceCreated: "instance.created.v1",
  InstanceConnected: "instance.connected.v1",
  InstanceDisconnected: "instance.disconnected.v1",
  InstanceLoggedOut: "instance.logged_out.v1",
  SessionActivated: "session.activated.v1",
  SessionExpired: "session.expired.v1",
  SessionRevoked: "session.revoked.v1",
  InboundMessageReceived: "message.received.v1",
  MessageAccepted: "message.accepted.v1",
  MessageDispatched: "message.dispatched.v1",
  MessageDelivered: "message.delivered.v1",
  MessageRead: "message.read.v1",
  MessageFailed: "message.failed.v1",
  MediaProcessed: "media.processed.v1",
  MediaFailed: "media.failed.v1",
  WebhookDeliverySucceeded: "webhook.delivery.succeeded.v1",
  WebhookDeliveryFailed: "webhook.delivery.failed.v1",
  WebhookDeliveryDeadLettered: "webhook.delivery.dead_lettered.v1",
  GuardrailBlocked: "guardrail.blocked.v1",
  GuardrailThrottled: "guardrail.throttled.v1",
  HealthDegraded: "health.degraded.v1",
  HealthRecovered: "health.recovered.v1",
};

const domainEventContractEntries = [
  contract(
    "InstanceCreated",
    "Instance",
    "instance.created",
    ["instance_id"],
    ["action_context"],
    "first_for_aggregate",
    "instance_id",
  ),
  contract(
    "InstanceQrRequired",
    "Instance",
    "instance.qr_required",
    ["instance_id", "action_required_reason"],
    ["pairing_attempt_ref"],
    "after_connect_intent",
    "pairing_attempt",
  ),
  contract(
    "InstanceConnected",
    "Instance",
    "instance.connected",
    ["instance_id", "readiness_status"],
    ["provider_profile_ref", "session_ref"],
    "after_created_not_destroyed",
    "latest_occurrence_wins",
  ),
  contract(
    "InstanceDisconnected",
    "Instance",
    "instance.disconnected",
    ["instance_id", "recoverability_category"],
    ["failure_category", "action_required_marker"],
    "after_connected_or_connecting",
    "event_identity",
  ),
  contract(
    "InstanceLoggedOut",
    "Instance",
    "instance.logged_out",
    ["instance_id", "logout_reason"],
    ["provider_failure_ref"],
    "after_active_or_connecting",
    "current_session_linkage",
  ),
  contract(
    "InstanceActionRequired",
    "Instance",
    "instance.action_required",
    ["instance_id", "action_required_reason"],
    ["recovery_hint"],
    "non_destroyed_only",
    "latest_reason_wins",
  ),
  contract(
    "InstanceDestroyed",
    "Instance",
    "instance.destroyed",
    ["instance_id"],
    ["destroy_reason", "actor_ref"],
    "last_for_aggregate",
    "instance_id",
  ),
  contract(
    "SessionPairingStarted",
    "Session",
    "session.pairing_started",
    ["session_id", "instance_id"],
    ["pairing_attempt_ref"],
    "before_pending_or_active",
    "pairing_attempt",
  ),
  contract(
    "SessionPending",
    "Session",
    "session.pending",
    ["session_id", "instance_id"],
    ["pairing_attempt_ref", "timeout_marker"],
    "before_active_expired_revoked",
    "latest_session_state",
  ),
  contract(
    "SessionActivated",
    "Session",
    "session.activated",
    ["session_id", "instance_id"],
    ["recovery_marker", "provider_profile_ref"],
    "after_pending_or_restore",
    "session_version",
  ),
  contract(
    "SessionExpired",
    "Session",
    "session.expired",
    ["session_id", "instance_id", "expiry_reason"],
    ["recovery_eligibility"],
    "after_pending_or_active",
    "latest_expiry_fact",
  ),
  contract(
    "SessionRevoked",
    "Session",
    "session.revoked",
    ["session_id", "instance_id", "revocation_reason"],
    ["action_required_marker"],
    "after_pending_or_active",
    "session_revocation",
  ),
  contract(
    "SessionRecoveryRequired",
    "Session",
    "session.recovery_required",
    ["session_id", "instance_id", "recovery_reason"],
    ["recovery_priority"],
    "after_failure_classification",
    "recovery_marker",
  ),
  contract(
    "SessionCleaned",
    "Session",
    "session.cleaned",
    ["session_id", "instance_id", "cleanup_reason"],
    ["retention_policy_ref"],
    "after_retention_trigger",
    "session_cleanup",
  ),
  contract(
    "InboundMessageReceived",
    "Message",
    "message.inbound_received",
    ["message_id", "instance_id", "message_type", "direction"],
    ["jid_ref", "media_ref", "safe_metadata"],
    "after_provider_translation",
    "message_id",
  ),
  contract(
    "UnsupportedMessageReceived",
    "Message",
    "message.unsupported_received",
    ["message_id", "instance_id", "unsupported_type_category"],
    ["safe_source_ref"],
    "after_provider_translation",
    "message_id",
  ),
  contract(
    "MessageAccepted",
    "Message",
    "message.accepted",
    ["message_id", "instance_id", "message_type", "guardrail_decision_id"],
    ["media_id", "idempotency_key"],
    "after_guardrail_passed",
    "message_id_or_idempotency_key",
  ),
  contract(
    "MessageRejected",
    "Message",
    "message.rejected",
    ["message_id", "instance_id", "failure_category"],
    ["guardrail_decision_id"],
    "before_queued",
    "message_id",
  ),
  contract(
    "MessageQueued",
    "Message",
    "message.queued",
    ["message_id", "instance_id", "job_ref"],
    ["retry_policy_ref"],
    "after_message_accepted",
    "job_or_message_idempotency",
  ),
  contract(
    "MessageProcessingStarted",
    "Message",
    "message.processing_started",
    ["message_id", "instance_id", "job_ref"],
    ["attempt_number"],
    "after_queued",
    "attempt_identity",
  ),
  contract(
    "MessageDispatched",
    "Message",
    "message.dispatched",
    ["message_id", "instance_id", "provider_ref", "delivery_status"],
    ["latency_category", "attempt_number"],
    "after_processing_started",
    "provider_ref_and_message_id",
  ),
  contract(
    "MessageDelivered",
    "Message",
    "message.delivered",
    ["message_id", "instance_id", "delivery_status"],
    ["provider_ref", "status_timestamp"],
    "after_dispatched_or_direct_delivery",
    "delivery_observation",
  ),
  contract(
    "MessageRead",
    "Message",
    "message.read",
    ["message_id", "instance_id", "delivery_status"],
    ["provider_ref", "status_timestamp"],
    "after_delivered_or_direct_read",
    "read_observation",
  ),
  contract(
    "MessageFailed",
    "Message",
    "message.failed",
    ["message_id", "instance_id", "failure_category", "safe_reason"],
    ["job_id", "provider_failure_classification"],
    "after_lifecycle_failure",
    "failure_category_and_reason",
  ),
  contract(
    "MessageCancelled",
    "Message",
    "message.cancelled",
    ["message_id", "instance_id", "cancellation_reason"],
    ["actor_context"],
    "before_terminal_delivery",
    "message_id",
  ),
  contract(
    "MediaAccepted",
    "MediaAsset",
    "media.accepted",
    ["media_id", "media_category", "retention_policy"],
    ["message_id"],
    "after_media_classification",
    "media_id",
  ),
  contract(
    "MediaProcessingStarted",
    "MediaAsset",
    "media.processing_started",
    ["media_id", "media_category", "job_id"],
    ["attempt_number"],
    "after_media_accepted",
    "attempt_identity",
  ),
  contract(
    "MediaProcessed",
    "MediaAsset",
    "media.processed",
    ["media_id", "media_category", "processing_status"],
    ["message_id", "safe_metadata_summary"],
    "after_processing_started",
    "media_processing_version",
  ),
  contract(
    "MediaAttached",
    "MediaAsset",
    "media.attached",
    ["media_id", "message_id"],
    ["attachment_role"],
    "after_media_processed",
    "media_message_association",
  ),
  contract(
    "MediaFailed",
    "MediaAsset",
    "media.failed",
    ["media_id", "failure_category", "safe_reason"],
    ["message_id", "job_id"],
    "after_media_work",
    "failure_category_and_reason",
  ),
  contract(
    "MediaExpired",
    "MediaAsset",
    "media.expired",
    ["media_id", "retention_policy"],
    ["expiry_reason"],
    "after_retention_window",
    "media_id",
  ),
  contract(
    "MediaCleaned",
    "MediaAsset",
    "media.cleaned",
    ["media_id", "cleanup_reason"],
    ["retention_policy_ref"],
    "after_processing_or_expiry",
    "media_id",
  ),
  contract(
    "DiagnosticCaptureRequested",
    "MediaAsset",
    "media.diagnostic_capture_requested",
    ["media_id", "capture_policy", "expiry"],
    ["actor_context"],
    "before_capture_begins",
    "media_id",
  ),
  contract(
    "GroupDiscovered",
    "Group",
    "group.discovered",
    ["group_id", "instance_id", "group_jid"],
    ["member_count", "metadata_summary"],
    "first_for_group",
    "group_id",
  ),
  contract(
    "GroupStatusUpdated",
    "Group",
    "group.status_updated",
    ["group_id", "instance_id", "group_status"],
    ["safe_reason"],
    "after_group_discovered",
    "latest_group_status",
  ),
  contract(
    "GroupMetadataUpdated",
    "Group",
    "group.metadata_updated",
    ["group_id", "instance_id", "metadata_revision"],
    ["actor_context"],
    "active_group_only",
    "metadata_revision",
  ),
  contract(
    "GroupMemberAdded",
    "Group",
    "group.member_added",
    ["group_id", "instance_id", "member_jid_ref"],
    ["actor_context", "member_role"],
    "active_group_only",
    "group_member_jid",
  ),
  contract(
    "GroupMemberRemoved",
    "Group",
    "group.member_removed",
    ["group_id", "instance_id", "member_jid_ref"],
    ["actor_context"],
    "active_group_only",
    "group_member_jid",
  ),
  contract(
    "GroupMemberRoleChanged",
    "Group",
    "group.member_role_changed",
    ["group_id", "instance_id", "member_jid_ref", "member_role"],
    ["actor_context"],
    "active_group_only",
    "group_member_role_version",
  ),
  contract(
    "GroupInviteLinkUpdated",
    "Group",
    "group.invite_link_updated",
    ["group_id", "instance_id", "invite_link_ref"],
    ["actor_context", "active"],
    "active_group_only",
    "invite_link_version",
  ),
  contract(
    "GroupLocalStateUpdated",
    "Group",
    "group.local_state_updated",
    ["group_id", "instance_id", "local_state"],
    ["actor_context"],
    "active_group_only",
    "latest_local_state",
  ),
  contract(
    "WebhookSubscriptionProposed",
    "WebhookSubscription",
    "webhook.subscription.proposed",
    ["webhook_id", "proposed_signal_selection", "safe_destination_ref"],
    ["actor_context"],
    "before_validation",
    "webhook_proposal_version",
  ),
  contract(
    "WebhookSubscriptionValidated",
    "WebhookSubscription",
    "webhook.subscription.validated",
    ["webhook_id", "validation_status"],
    ["signal_selection_summary"],
    "before_activation_or_delivery",
    "webhook_version",
  ),
  contract(
    "WebhookSubscriptionActivated",
    "WebhookSubscription",
    "webhook.subscription.activated",
    ["webhook_id", "activation_status"],
    ["signal_selection_summary"],
    "after_validation",
    "latest_subscription_version",
  ),
  contract(
    "WebhookSubscriptionSuspended",
    "WebhookSubscription",
    "webhook.subscription.suspended",
    ["webhook_id", "suspension_reason"],
    ["recovery_hint"],
    "after_active",
    "webhook_id",
  ),
  contract(
    "WebhookSubscriptionInvalidated",
    "WebhookSubscription",
    "webhook.subscription.invalidated",
    ["webhook_id", "invalid_reason"],
    ["validation_failure_category"],
    "any_configured_state",
    "latest_invalid_state",
  ),
  contract(
    "WebhookSubscriptionRetired",
    "WebhookSubscription",
    "webhook.subscription.retired",
    ["webhook_id", "retirement_reason"],
    ["actor_context"],
    "final_for_subscription_version",
    "webhook_id",
  ),
  contract(
    "WebhookDeliveryScheduled",
    "WebhookDelivery",
    "webhook.delivery.scheduled",
    ["webhook_delivery_id", "webhook_id", "source_signal_ref"],
    ["retry_policy", "idempotency_key"],
    "after_valid_subscription",
    "delivery_id_or_idempotency_key",
  ),
  contract(
    "WebhookDeliveryStarted",
    "WebhookDelivery",
    "webhook.delivery.started",
    ["webhook_delivery_id", "attempt_number"],
    ["job_id"],
    "after_scheduled",
    "attempt_identity",
  ),
  contract(
    "WebhookDeliverySucceeded",
    "WebhookDelivery",
    "webhook.delivery.succeeded",
    ["webhook_delivery_id", "webhook_id", "attempt_number"],
    ["receiver_status_class"],
    "terminal_after_started",
    "webhook_delivery_id",
  ),
  contract(
    "WebhookDeliveryRetryScheduled",
    "WebhookDelivery",
    "webhook.delivery.retry_scheduled",
    ["webhook_delivery_id", "retry_policy", "attempt_number", "failure_category"],
    ["next_retry_window"],
    "after_failed_attempt",
    "retry_entry",
  ),
  contract(
    "WebhookDeliveryFailed",
    "WebhookDelivery",
    "webhook.delivery.failed",
    ["webhook_delivery_id", "failure_category", "safe_reason"],
    ["attempt_number"],
    "after_delivery_attempts",
    "webhook_delivery_id",
  ),
  contract(
    "WebhookDeliveryDeadLettered",
    "WebhookDelivery",
    "webhook.delivery.dead_lettered",
    ["webhook_delivery_id", "dead_letter_reason"],
    ["retry_summary"],
    "after_retry_exhaustion",
    "webhook_delivery_id",
  ),
  contract(
    "WebhookDeliveryCancelled",
    "WebhookDelivery",
    "webhook.delivery.cancelled",
    ["webhook_delivery_id", "cancellation_reason"],
    ["source_signal_ref"],
    "before_terminal_delivery",
    "webhook_delivery_id",
  ),
  contract(
    "GuardrailEvaluated",
    "GuardrailDecision",
    "guardrail.evaluated",
    ["guardrail_decision_id", "evaluated_intent_ref"],
    ["risk_summary"],
    "before_outcome",
    "guardrail_decision_id",
  ),
  contract(
    "GuardrailPassed",
    "GuardrailDecision",
    "guardrail.passed",
    ["guardrail_decision_id", "outcome"],
    ["safe_reason"],
    "after_evaluated",
    "guardrail_decision_id",
  ),
  contract(
    "GuardrailBlocked",
    "GuardrailDecision",
    "guardrail.blocked",
    ["guardrail_decision_id", "outcome", "safe_reason"],
    ["abuse_risk_classification"],
    "after_evaluated",
    "guardrail_decision_id",
  ),
  contract(
    "GuardrailThrottled",
    "GuardrailDecision",
    "guardrail.throttled",
    ["guardrail_decision_id", "outcome", "rate_limit_classification"],
    ["retry_after_category"],
    "after_evaluated",
    "guardrail_decision_id",
  ),
  contract(
    "GuardrailActionRequired",
    "GuardrailDecision",
    "guardrail.action_required",
    ["guardrail_decision_id", "action_required_reason"],
    ["risk_summary"],
    "after_evaluated",
    "guardrail_decision_id",
  ),
  contract(
    "ProviderProfileSupported",
    "ProviderProfile",
    "provider_profile.supported",
    ["provider_id", "capability_summary"],
    ["compatibility_notes"],
    "after_compatibility_check",
    "provider_profile_version",
  ),
  contract(
    "ProviderProfileDegraded",
    "ProviderProfile",
    "provider_profile.degraded",
    ["provider_id", "degradation_reason"],
    ["capability_impact_summary"],
    "after_supported_or_candidate",
    "latest_status_wins",
  ),
  contract(
    "ProviderProfileUnsupported",
    "ProviderProfile",
    "provider_profile.unsupported",
    ["provider_id", "unsupported_reason"],
    ["capability_impact_summary"],
    "after_compatibility_check",
    "latest_status_wins",
  ),
  contract(
    "ProviderCapabilityChanged",
    "ProviderProfile",
    "provider_profile.capability_changed",
    ["provider_id", "capability_category", "previous_classification", "new_classification"],
    ["compatibility_notes"],
    "after_capability_update",
    "provider_capability_version",
  ),
  contract(
    "ProviderFailureClassified",
    "ProviderProfile",
    "provider_profile.failure_classified",
    ["provider_id", "failure_category", "affected_capability"],
    ["safe_provider_ref"],
    "after_infrastructure_translation",
    "observation_ref",
  ),
  contract(
    "WorkerJobQueued",
    "WorkerJob",
    "worker.job.queued",
    ["job_id", "owner_context_ref", "job_type"],
    ["retry_policy"],
    "first_for_job",
    "job_id",
  ),
  contract(
    "WorkerJobReserved",
    "WorkerJob",
    "worker.job.reserved",
    ["job_id", "reservation_ref"],
    ["attempt_number"],
    "after_queued",
    "reservation_ref",
  ),
  contract(
    "WorkerJobStarted",
    "WorkerJob",
    "worker.job.started",
    ["job_id", "attempt_number"],
    ["worker_runtime_ref"],
    "after_reserved",
    "attempt_identity",
  ),
  contract(
    "WorkerJobCompleted",
    "WorkerJob",
    "worker.job.completed",
    ["job_id", "owner_context_ref"],
    ["result_summary"],
    "after_started",
    "job_id",
  ),
  contract(
    "WorkerJobRetryScheduled",
    "WorkerJob",
    "worker.job.retry_scheduled",
    ["job_id", "retry_policy", "failure_category"],
    ["next_retry_window"],
    "after_failed_attempt",
    "retry_entry",
  ),
  contract(
    "WorkerJobDead",
    "WorkerJob",
    "worker.job.dead",
    ["job_id", "dead_reason"],
    ["attempt_summary"],
    "after_retry_exhaustion",
    "job_id",
  ),
  contract(
    "WorkerJobRecoveryRequired",
    "WorkerJob",
    "worker.job.recovery_required",
    ["job_id", "recovery_reason"],
    ["recovery_priority"],
    "after_dead_or_unsafe_state",
    "recovery_marker",
  ),
  contract(
    "AccessGranted",
    "AccessDecision",
    "access.granted",
    ["access_decision_id", "actor_ref", "capability"],
    ["target_aggregate_ref"],
    "before_privileged_mutation",
    "access_decision_id",
  ),
  contract(
    "AccessDenied",
    "AccessDecision",
    "access.denied",
    ["access_decision_id", "actor_ref", "capability", "safe_reason"],
    ["target_aggregate_ref"],
    "before_stopped_mutation",
    "access_decision_id",
  ),
  contract(
    "PrivilegedActionMarked",
    "AccessDecision",
    "access.privileged_action_marked",
    ["access_decision_id", "capability", "privilege_category"],
    ["target_aggregate_ref"],
    "before_action_execution",
    "access_decision_id",
  ),
  contract(
    "SecretAccessRequested",
    "AccessDecision",
    "access.secret_access_requested",
    ["access_decision_id", "secret_access_reason_category"],
    ["target_secret_ref"],
    "before_secret_boundary_access",
    "access_decision_id",
  ),
  contract(
    "AccessDecisionExpired",
    "AccessDecision",
    "access.decision_expired",
    ["access_decision_id", "actor_ref", "capability"],
    ["expiry_reason"],
    "after_decision_scope",
    "access_decision_id",
  ),
  contract(
    "AuditRecordRequested",
    "AuditRecord",
    "audit.record_requested",
    ["audit_record_id", "source_signal_ref", "audit_category"],
    ["actor_context"],
    "after_auditable_fact",
    "audit_record_id",
  ),
  contract(
    "AuditRecorded",
    "AuditRecord",
    "audit.recorded",
    ["audit_record_id", "audit_category", "retention_category"],
    ["redaction_marker"],
    "after_request",
    "audit_record_id",
  ),
  contract(
    "AuditRedactionApplied",
    "AuditRecord",
    "audit.redaction_applied",
    ["audit_record_id", "redaction_marker"],
    ["redaction_reason"],
    "before_recorded_where_applicable",
    "redaction_marker",
  ),
  contract(
    "AuditRetentionExpired",
    "AuditRecord",
    "audit.retention_expired",
    ["audit_record_id", "retention_category"],
    ["expiry_reason"],
    "after_retention_window",
    "audit_record_id",
  ),
  contract(
    "HealthStatusChanged",
    "HealthStatus",
    "health.status_changed",
    ["health_status_id", "health_subject", "health_category"],
    ["cause_category"],
    "after_source_signal_classification",
    "latest_classification_wins",
  ),
  contract(
    "HealthDegraded",
    "HealthStatus",
    "health.degraded",
    ["health_status_id", "health_subject", "degradation_cause"],
    ["action_required_marker"],
    "after_healthy_or_worsening",
    "latest_degradation_wins",
  ),
  contract(
    "HealthRecovered",
    "HealthStatus",
    "health.recovered",
    ["health_status_id", "health_subject"],
    ["previous_cause_category"],
    "after_degraded_unavailable_or_action_required",
    "health_status_id",
  ),
  contract(
    "HealthActionRequired",
    "HealthStatus",
    "health.action_required",
    ["health_status_id", "health_subject", "action_reason"],
    ["recovery_hint_category"],
    "after_source_classification",
    "action_marker",
  ),
  contract(
    "ConfigurationValidated",
    "ConfigurationSnapshot",
    "configuration.validated",
    ["configuration_snapshot_id", "safety_classification"],
    ["changed_setting_categories"],
    "before_activation",
    "configuration_snapshot_id",
  ),
  contract(
    "ConfigurationRejected",
    "ConfigurationSnapshot",
    "configuration.rejected",
    ["configuration_snapshot_id", "rejection_reason"],
    ["unsafe_categories"],
    "after_validation",
    "configuration_snapshot_id",
  ),
  contract(
    "ConfigurationActivated",
    "ConfigurationSnapshot",
    "configuration.activated",
    ["configuration_snapshot_id", "active_marker"],
    ["superseded_snapshot_ref"],
    "after_validated",
    "latest_active_snapshot",
  ),
  contract(
    "ConfigurationGuardrailBypassRejected",
    "ConfigurationSnapshot",
    "configuration.guardrail_bypass_rejected",
    ["configuration_snapshot_id", "guardrail_category", "safe_reason"],
    ["actor_context"],
    "during_validation",
    "configuration_snapshot_id",
  ),
  contract(
    "ConfigurationSuperseded",
    "ConfigurationSnapshot",
    "configuration.superseded",
    ["configuration_snapshot_id", "new_snapshot_ref"],
    ["reason_category"],
    "after_new_activation",
    "configuration_snapshot_id",
  ),
  contract(
    "TelemetryCaptured",
    "TelemetrySignal",
    "telemetry.captured",
    ["telemetry_signal_id", "source_signal_ref", "data_classification"],
    ["correlation_context"],
    "before_sanitization",
    "telemetry_signal_id",
  ),
  contract(
    "TelemetrySanitized",
    "TelemetrySignal",
    "telemetry.sanitized",
    ["telemetry_signal_id", "redaction_marker"],
    ["projection_category"],
    "after_captured",
    "telemetry_signal_id",
  ),
  contract(
    "TelemetryDropped",
    "TelemetrySignal",
    "telemetry.dropped",
    ["telemetry_signal_id", "drop_reason"],
    ["source_context_ref"],
    "after_captured_or_classified",
    "telemetry_signal_id",
  ),
  contract(
    "TelemetryProjected",
    "TelemetrySignal",
    "telemetry.projected",
    ["telemetry_signal_id", "projection_category"],
    ["safe_projection_category"],
    "after_sanitized",
    "projection_target_and_signal_id",
  ),
] as const;

export const domainEventContracts = Object.freeze(
  Object.fromEntries(
    domainEventContractEntries.map((eventContract) => [eventContract.eventName, eventContract]),
  ),
) as Readonly<Record<DomainEventName, DomainEventContract>>;

export function getDomainEventContract(eventName: DomainEventName): DomainEventContract {
  return domainEventContracts[eventName];
}

export function listDomainEventContracts(): readonly DomainEventContract[] {
  return Object.freeze([...domainEventContractEntries]);
}

export function isApprovedIntegrationEventName(value: string): value is IntegrationEventName {
  return approvedIntegrationEventNames.includes(value as IntegrationEventName);
}

export function createDomainEventContract(input: DomainEventContractInput): DomainEventContract {
  const eventName = createStringUnionValue(input.eventName, domainEventNames, "DomainEventName");
  const aggregateType = createStringUnionValue(
    input.aggregateType,
    domainAggregateTypes,
    "DomainAggregateType",
  );
  const integrationEventName =
    input.integrationEventName === undefined
      ? undefined
      : createStringUnionValue(
          input.integrationEventName,
          approvedIntegrationEventNames,
          "IntegrationEventName",
        );

  return freezeContract({
    eventName,
    signalName: createSafeDomainCode(input.signalName, "DomainEventContract.signalName"),
    version: createStringUnionValue(input.version, eventContractVersions, "EventContractVersion"),
    aggregateType,
    dataClassification: createStringUnionValue(
      input.dataClassification,
      eventDataClassifications,
      "EventDataClassification",
    ),
    requiredData: freezeSafeCodes(input.requiredData, "DomainEventContract.requiredData"),
    optionalData: freezeSafeCodes(input.optionalData ?? [], "DomainEventContract.optionalData"),
    orderingRequirement: createSafeDomainCode(
      input.orderingRequirement,
      "DomainEventContract.orderingRequirement",
    ),
    idempotencyRequirement: createSafeDomainCode(
      input.idempotencyRequirement,
      "DomainEventContract.idempotencyRequirement",
    ),
    ...(integrationEventName === undefined ? {} : { integrationEventName }),
  });
}

function contract(
  eventName: DomainEventName,
  aggregateType: DomainAggregateType,
  signalName: string,
  requiredData: readonly string[],
  optionalData: readonly string[],
  orderingRequirement: string,
  idempotencyRequirement: string,
): DomainEventContract {
  return createDomainEventContract({
    eventName,
    signalName,
    version: "v1",
    aggregateType,
    dataClassification: "internal",
    requiredData,
    optionalData,
    orderingRequirement,
    idempotencyRequirement,
    ...(integrationEventByDomainEvent[eventName] === undefined
      ? {}
      : { integrationEventName: integrationEventByDomainEvent[eventName] }),
  });
}

function freezeSafeCodes(values: readonly string[], label: string): readonly string[] {
  return Object.freeze(values.map((value) => createSafeDomainCode(value, label)));
}

function freezeContract(contractValue: DomainEventContract): DomainEventContract {
  return Object.freeze({
    ...contractValue,
    requiredData: Object.freeze([...contractValue.requiredData]),
    optionalData: Object.freeze([...contractValue.optionalData]),
  });
}
